export enum ErrorMessage {
  PHONE_REQUIRED = 'Phone number is required',
  INVALID_PHONE_FORMAT = 'Phone must be in international format (e.g. +998901234567)',
  PHONE_AND_CODE_REQUIRED = 'Phone and code are required',
  INVALID_OTP_FORMAT = 'Code must be exactly 6 digits',
  OTP_EXPIRED = 'OTP expired or not found. Please request a new code.',
  INVALID_OTP = 'Invalid verification code',
  ACCOUNT_BANNED = 'This account has been banned',
  REFRESH_TOKEN_REQUIRED = 'Refresh token is required',
  INVALID_REFRESH_TOKEN = 'Invalid or expired refresh token',
  REFRESH_TOKEN_REVOKED = 'Refresh token has been revoked',
  EMAIL_REQUIRED = 'Email is required',
  PASSWORD_REQUIRED = 'Password is required',
  INVALID_EMAIL = 'Must be a valid email address',
  EMAIL_AND_PASSWORD_REQUIRED = 'Email and password are required',
  INVALID_CREDENTIALS = 'Invalid credentials',
  TELEGRAM_GATEWAY_ERROR = 'Telegram Gateway error',
  USERNAME_REQUIRED = 'Username is required',
  USERNAME_INVALID = 'Username must be 3-20 chars and contain only lowercase letters, digits, _ or .',
  USERNAME_TAKEN = 'Username is already taken',
  FIRSTNAME_REQUIRED = 'First name is required',
  FIRSTNAME_TOO_LONG = 'First name must be at most 50 characters',
  LASTNAME_TOO_LONG = 'Last name must be at most 50 characters',
  INVALID_GENDER = 'Gender must be male or female',
  INVALID_BIRTHDAY = 'Birthday must be a valid date in DD/MM/YYYY format',
  UNDERAGE = 'You must be at least 13 years old',
  AVATAR_TOO_LARGE = 'Avatar file must be smaller than 5MB',
  AVATAR_INVALID_TYPE = 'Avatar must be an image file',
  PROFILE_ALREADY_COMPLETE = 'Profile is already complete',
  USER_NOT_FOUND = 'User not found',
  EVENT_NOT_FOUND = 'Event not found',
  ACTIVITY_NOT_FOUND = 'Activity not found',
  ALREADY_JOINED = 'You have already joined this event',
  EVENT_FULL = 'This event is full',
  NOT_JOINED = 'You have not joined this event',
}

export enum SuccessMessage {
  OTP_SENT = 'OTP sent successfully',
  AUTH_SUCCESS = 'Authentication successful',
  LOGGED_OUT = 'Logged out successfully',
  PROFILE_COMPLETED = 'Profile completed successfully',
}
